### ISSUE TITLE
YAML: Allow to store dates without time

### ISSUE THREAD

**Issue by oscarotero** [denoland/std#5680]
**Is your feature request related to a problem? Please describe.**

I want to create a front matter with a code like this:

```yml
---
title: Post title
date: 2024-09-01
---
```

But YAML export the `date` value in this way:

```yml
---
title: Post title
date: 2024-09-01T19:00:00Z
---
```

The only way I found to save only the date (without time) was to convert the value to a string:

```yml
---
title: Post title
date: "2024-09-01"
---
```

But then this value is not parsed as Date.

**Describe the solution you'd like**

A way to store dates without including the time. As an idea, maybe detecting if the object is a `Temporal.PlainDate` instance.
